# Generated by Django 3.2.8 on 2021-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courdiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('rowid', models.CharField(max_length=10)),
                ('final_opt', models.CharField(choices=[('dept', 'dept'), ('group', 'group'), ('courdiv', 'courdiv')], max_length=255)),
            ],
            options={
                'ordering': ('rowid',),
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('rowid', models.CharField(max_length=255)),
                ('courdiv', models.ManyToManyField(to='scrap.Courdiv')),
            ],
            options={
                'ordering': ('rowid',),
            },
        ),
    ]
