# Generated by Django 3.2.8 on 2021-10-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectivesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('rowid', models.CharField(max_length=255)),
                ('courdiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scrap.courdiv')),
            ],
            options={
                'ordering': ('rowid',),
            },
        ),
    ]
