# Generated by Django 3.2.8 on 2021-10-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20211009_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='scrap.college'),
        ),
        migrations.AlterField(
            model_name='department',
            name='courdiv',
            field=models.ManyToManyField(related_name='depts', to='scrap.Courdiv'),
        ),
    ]
