# Generated by Django 3.2.8 on 2021-10-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20211010_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rowid', models.CharField(max_length=5)),
                ('campus', models.CharField(max_length=255)),
                ('dept', models.CharField(max_length=255)),
                ('cour_cd', models.CharField(max_length=255)),
                ('cour_cls', models.CharField(max_length=255)),
                ('isu_nm', models.CharField(max_length=255)),
                ('prof_nm', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=5)),
                ('credit_time', models.CharField(max_length=255)),
                ('time_room', models.CharField(max_length=255)),
                ('relative_yn', models.CharField(max_length=5)),
                ('lmt_ym', models.CharField(max_length=5)),
                ('exch_cor_yn', models.CharField(max_length=5)),
                ('attend_free_yn', models.CharField(max_length=5)),
                ('no_supervisor_yn', models.CharField(max_length=5)),
                ('flexible_term_yn', models.CharField(max_length=5)),
                ('searched_by_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scrap.courdiv')),
                ('searched_by_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scrap.department')),
                ('searched_by_g', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scrap.electivesgroup')),
            ],
        ),
    ]
