# Generated by Django 3.2.8 on 2021-10-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lmt_ym',
            new_name='lmt_yn',
        ),
    ]
