# Generated by Django 3.2.8 on 2021-10-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_rename_lmt_ym_course_lmt_yn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='course',
            name='searched_by_c',
        ),
        migrations.AddField(
            model_name='course',
            name='courdiv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scrap.courdiv'),
            preserve_default=False,
        ),
    ]
